test_data_name: tmQMg_ligands_bo_dl_lmbp
modeldir: runs/tmQMg_tzvp_homo_lumo_gap_ligands_bo/train/2024_08_13_15_26_02.015120
write_interval: batch_and_epoch
print_config: true
output_result_file: true
outputFileName: tmQMg_ob_bs_test_gap_LMBP
new_data_flag: false
run:
  work_dir: ${hydra:runtime.cwd}/src
  execute_dir: ${hydra:runtime.cwd}
  data_dir: ${run.execute_dir}/database
  datasource_dir: ${run.execute_dir}/datasource
  config_dir: ${run.execute_dir}/configs
  path: runs
  id: ${datetime:1}
  output_root_dir: null
trainer:
  _target_: src.train.BaseTrainer
  devices: auto
  min_epochs: null
  max_epochs: 100000
  enable_model_summary: true
  profiler: null
  gradient_clip_val: 0
  val_check_interval: 1.0
  check_val_every_n_epoch: 1
  num_sanity_val_steps: 0
  fast_dev_run: false
  overfit_batches: 0
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  detect_anomaly: false
  precision: 32
  accelerator: auto
  num_nodes: 1
  deterministic: false
  ckpt_path: null
  enable_autorun: true
  retry_times_total_limit: 20
  retry_times_sub_limit: 10
  rerun_start_on_epoch: 10
  rerun_when_loss: 5.0
main:
  optimizer_cls: torch.optim.AdamW
  optimizer_args:
    lr: ${globals.lr}
    weight_decay: 0.0
  scheduler_cls: src.train.ReduceLROnPlateau
  scheduler_monitor: val_loss
  scheduler_args:
    mode: min
    factor: 0.5
    patience: 25
    threshold: 0.0001
    threshold_mode: rel
    cooldown: 10
    min_lr: 0.0
    smoothing_factor: 0.0
  _target_: src.main.BsAtomisticTask
  outputs:
  - _target_: src.main.ModelOutput
    name: ${globals.property}
    loss_fn:
      _target_: torch.nn.MSELoss
    metrics:
      mae:
        _target_: torchmetrics.regression.MeanAbsoluteError
      rmse:
        _target_: torchmetrics.regression.MeanSquaredError
        squared: false
    loss_weight: 1.0
  warmup_steps: 0
data:
  _target_: src.datasets.tmQMg_obabel_bondstep_no_pad_ligands
  datapath: ${run.data_dir}/${globals.dataname}.db
  data_workdir: /tmp/sean0204/${run.id}
  batch_size: 32
  num_train: 48639
  num_val: 6079
  num_test: null
  num_workers: 4
  num_val_workers: 4
  num_test_workers: 4
  pin_memory: true
  outputdir: ${modeldir}
  split_file: ${modeldir}/split.npz
  smi_datapath: ${run.datasource_dir}/tmQMg_ob.smi
  y_datapath: ${run.datasource_dir}/tmQMg_properties_and_targets.csv
  regressionTransformer: false
  property_units:
    tzvp_dispersion_energy: eV
    tzvp_electronic_energy: eV
    tzvp_homo_energy: eV
    tzvp_lumo_energy: eV
    tzvp_homo_lumo_gap: eV
  split: test
  transforms:
  - _target_: src.transform.BondStepLigandNeighborNoPadList
  - _target_: src.transform.CastTo32
globals:
  cutoff: 10.0
  lr: 0.0001
  property: tzvp_homo_lumo_gap
  dataname: tmQMg_ligands_bo_dl_lmbp
hydra:
  job:
    chdir: false
  run:
    dir: ${modeldir}
  output_subdir: null
